### PR TITLE
added first try to SentimentTests

### PR DESCRIPTION
**Pull request by ashwoodaa**

### CODE REVIEW

**Comment by carter-harris** [comment]
Per Ryan, we are using too much logic in our test.  We need to use "dummy" inputs for "dummy" outputs. 

Below they hard code stuff just to see if the input meets the output. We will not have the tokenizer stuff to test in our Test files so we need to use dummy stuff. Make it fun and unique!

Ex. 

```
def test_creating_dictionaries(self):
    empty_dict = dict()
    self.assertEqual(dict, type(empty_dict))
    self.assertDictEqual({}, empty_dict)
    self.assertEqual(0, len(empty_dict))


def test_accessing_dictionaries(self):
    babel_fish = { 'one': 'uno', 'two': 'dos' }
    self.assertEqual('uno', babel_fish['one'])
    self.assertEqual('dos', babel_fish['two'])


def test_non_parallel_assignment(self):
    names = ["John", "Smith"]
    self.assertEqual(names, names)

def test_parallel_assignments(self):
    first_name, last_name = ["John", "Smith"]
    self.assertEqual(first_name, first_name)
    self.assertEqual(last_name, last_name)
```

**Comment by Jessicashinjo** [comment]
Let's go ahead and split the Lexicon into different files to resolve the merge conflict and help prevent future merge conflicts.

**Comment by Jessicashinjo** [comment]
Everything looks good!

**Comment by carter-harris** [comment]
👍

**Comment by keithbradley1** [comment]
great stuff AA! 👍

**Pull request merged**
