### PR TITLE
draft TestMessageTokenizer.py

### PR DESCRIPTION
**Pull request by carter-harris**
Rough draft of initial test for TestMessageTokenizer.py

Pull request to end brainstorming off Floobits to work in a team of two on the file.

### CODE REVIEW

**Comment by ashwoodaa** [comment]
:+1:

**Comment by Jessicashinjo** [comment]
Looks good. I'll finish it up once it's merged in. 👍

**Comment by keithbradley1** [comment]
👍

**Comment by carter-harris** [comment]
Jessica, we are going to kill this test 🔪

**Pull request merged**
